---
- name: Lvm | creating logical volume
  when:
    - vg.state is defined
    - vg.state == "present"
    - lv is defined
    - lv != 'None'
    - lv.state is defined
    - lv.state == "present"
  register: lvchanged
  community.general.lvol:
    vg: "{{ vg.vg_name }}"
    lv: "{{ lv.lv_name }}"
    size: "{{ lv.size }}"
    shrink: false
    opts: "{{ lv.opts | default('') }}"
    state: present


- name: Lvm | configuring filesystem
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/create_fs.yml
