---
- name: lvm, debian | update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: lvm, debian | installing required packages
  ansible.builtin.apt:
    name:
      - lvm2
      - scsitools
      - xfsprogs
    state: present

- name: lvm, debian | checking for scsi devices
  ansible.builtin.command: sg_scan
  register: scsi_devices
  changed_when: false

- name: lvm, debian | rescanning for new disks added
  ansible.builtin.command: /sbin/rescan-scsi-bus
  changed_when: false
  when: scsi_devices['stdout'] | length

- ansible.builtin.include_tasks:
    file: tasks/sub-tasks/manage_lvm.yml
  when:
    - lvm_vg_list is defined
    - lvm_configure | bool
